@Vessels_HostAddress = http://localhost:5294

GET {{Vessels_HostAddress}}/api/vessels/
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFxdW9uIiwic3ViIjoiYXF1b24iLCJqdGkiOiI5YTc0N2VkMCIsInJvbGUiOiJBZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUyODQiLCJodHRwczovL2xvY2FsaG9zdDo0NDMwNiIsImh0dHA6Ly9sb2NhbGhvc3Q6NTI5NCIsImh0dHBzOi8vbG9jYWxob3N0OjcyMTIiXSwibmJmIjoxNzIzNTAyMzk5LCJleHAiOjE3MzE0NTExOTksImlhdCI6MTcyMzUwMjQwMCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.yz5YJ4Ph2dPid4kdstRiskid561F97kI03cQ5XrvIP0.eyJ1bmlxdWVfbmFtZSI6ImFxdW9uIiwic3ViIjoiYXF1b24iLCJqdGkiOiI5YTc0N2VkMCIsInJvbGUiOiJBZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUyODQiLCJodHRwczovL2xvY2FsaG9zdDo0NDMwNiIsImh0dHA6Ly9sb2NhbGhvc3Q6NTI5NCIsImh0dHBzOi8vbG9jYWxob3N0OjcyMTIiXSwibmJmIjoxNzIzNTAyMzk5LCJleHAiOjE3MzE0NTExOTksImlhdCI6MTcyMzUwMjQwMCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.yz5YJ4Ph2dPid4kdstRiskid561F97kI03cQ5XrvIP0
###
